name: Auto Merge to dev after Go Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  test-and-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # 필요한 버전으로 조정

      - name: Run Go tests
        run: |
          go mod tidy
          go test ./...

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}